config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :reviews
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/products/:id/buy' => 'products#buy'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/cart' => 'products#cart'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :show, :all
    can :buy, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true, greater_than: 0}
  has_many :reviews
  has_many :purchased_products
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

app/models/purchased_product.rb
class PurchasedProduct < ApplicationRecord
  belongs_to :product
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_many :products
  has_many :purchased_products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_filter :authorize
  before_action :set_product, only: [:show, :edit, :update, :destroy, :buy]
  


  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def buy
    @purchase = current_user.purchased_products.build(product: @product)
    if @purchase.save
      redirect_to @product, notice: 'Product was successfully purchased.'
    else
      redirect_back(fallback_location: root_path)
    end
  end


  def cart
    @products = []
    @total = 0;
    @purchases = current_user.purchased_products
    @purchases.each do |purchase|
      @products << Product.find(purchase.product_id)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name,:image,:description, :price_in_cents)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  #before_filter :authorize
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:comment, :product_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @products = Product.all 
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
    # Save the user id inside the browser cookie. This is how we keep the user
    # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/products'
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/products'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_controller_helper.rb
module UserControllerHelper
end

app/views/layouts/_header.html.erb
<html>
  <head>
    <title>WebZoo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Sedgwick+Ave+Display" rel="stylesheet">
  </head>
  <div id="container">
    <div id= "header">
      <header>
        <ul class= "a-main-header__homepage">
          <li class="text"><p>WebZoo: One stop shop for your exotic animal needs!</p></li>
          <li class="icon"><i class="fa fa-user-o" aria-hidden="true" fa-5x></i></li>
        </ul>
        <div class="signin">
        <p>Hello. Sign in</p>
        <%= form_tag '/login' do %>
        <i class="fa fa-envelope" aria-hidden="true"></i> Email <%= text_field_tag :email %>
        <i class="fa fa-key" aria-hidden="true"></i>Password <%= password_field_tag :password %>
        <%= submit_tag "Login" %>
        <% end %>
        <% if current_user %>
       Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
        <% else %>
          <%= link_to 'Signup', '/signup' %>
        <% end %>
        </div>
      </header>
</div>
  <div id="Wrapper"
      <div id="app_promotion_banner" class="box-trans-white pad-top-bottom" style="border-bottom:1px solid #ffffff;"
              <div class="container clearfix">
              <div class="left pad-top-bottom text-shadow-none"><p> WebZoo is the simplest way to buy and sell invasive and exotic animals. Look for the free app coming soon!!</p></div>
              <div class="right">
                  <ul class="horizontal space-none type-none text-center">
                  </ul>
              </div>
              </div>
            </div>
          </div>
<div id="body">
      <body>
        <%= yield %>
      </body>
    </div>
    <div id="footer">
      <div class = "footer">
      </div>
    </div>
  </div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebZoo</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Sedgwick+Ave+Display" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div id="container">
    <div id= "header">
      <header>
        <ul class= "a-main-header__homepage">
          <li class="text"><p>WebZoo: One stop shop for your exotic animal needs!</p></li>
          <li class="icon"><i class="fa fa-user-o" aria-hidden="true" fa-5x></i></li>
        </ul>
        <div class="signin">
        <p>Hello. Sign in</p>
        <%= form_tag '/login' do %>
        <i class="fa fa-envelope" aria-hidden="true"></i> Email <%= text_field_tag :email %>
        <i class="fa fa-key" aria-hidden="true"></i>Password <%= password_field_tag :password %>
        <%= submit_tag "Login" %>
        <% end %>
        <% if current_user %>
      Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %> | <%= link_to "Cart", '/cart' %> | <%= link_to "Listings", '/products'%> | <%= link_to "Comments", '/reviews'%>
        <% else %>
          <%= link_to 'Signup', '/signup' %>
        <% end %>
        <div class="homebutton">
        <a href="https://webzoo.herokuapp.com/"><i class="fa fa-home fa-2x"></i></a>
        </div
          </header>
        </div>
      <body>
        <%= yield %>
      </body>
    </div>
    <div id="footer">
      <div class = "footer">
      </div>
    </div>
  </div>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :price_in_cents %>
    <%= form.number_field :price_in_cents, id: :product_price_in_cents %>
  </div>

  <div class="field">
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/cart.html.erb
<h1>Shopping Cart</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.formatted_price %></td>
      </tr>
      <%@total += product.price_in_cents%>
    <% end %>
    <tr>
      <td>--------</td>
      <td>---------------------------------------</td>
      <td>--------</td>
    </tr>
    <tr>
      <td>Subtotal</td>
      <td></td>
      <td><%= @total.to_f / 100%></td>
    </tr>
  </tbody>
</table>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<header>
</header>

<body>
<p id="notice"><%= notice %></p>
<h1 class="productcount">There are currently <%= Product.count %> Exotic Animals for sale </h1>

<div style="overflow-x:auto;">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="2">Options</th>
      <th>Photos</th>
    </tr>
  </thead>
  <tbody>
      <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.formatted_price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Buy', "/products/#{product.id}/buy" %></td>
        <td><%= image_tag(product.image.http://webzooheroku.s3.amazonaws.com, width:100)%>
        <%if !current_user.products.map(&:id).include?(product.id)%>
        <%if !current_user.purchased_products.map(&:product_id).include?(product.id)%>
        <% if can? :edit, @product %>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <% if can? :destroy, @product %>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
          <% end %>
          <% end %>
          <% end %>
          <% end %>
      <%end%>
    </tbody>
  </table>
</div>
<br>
</body>
<div class="new_product">
<%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <div class="container clearfix">
    <div id="Wrapper"
    <div id="app_promotion_banner" class="box-trans-white pad-top-bottom" style="border-bottom:1px solid #ffffff;"
                    <div class="container clearfix">
                    <div class="left pad-top-bottom text-shadow-none"><div>
                    </div>
                    </div>
                    </div>
    </div>
    </div>
  </head>
  <div id="header_ad">
    <div class="applicationtext"<p> WebZoo is the simplest way to buy and sell invasive and exotic animals. Look for the free app coming soon!!</p></div>
    <div class="right">
        <ul class="horizontal space-none type-none text-center">
        </ul>
  </div>
</div>
  <body>
    <div class="container clearfix" style="margin-top:20px;">
      <div class="right text-center">
        <div class="box-sidebar">
                          <div class="header">ASKING PRICE </div>
                          <div class="pricebox">
                              <sup style="font-size:1.5em" class="color-branch">$</sup>
                              <span class="size-large-xx color-gray-darker medium"><%= @product.formatted_price %></span>
                            </div>
                          </div>
                        </div>
      <div class="text-center size-medium pad-more-left-right">
        </div>
      </div>
    <div class="left" style="width:620px;">
      <div class="box-main-alt">
        <div class="productimage">
          <%= image_tag(@product.image.http://webzooheroku.s3.amazonaws.com, id:"productpage")%>
        </div>

        <div class="left base-size medium color-gray-darker" style="width: 80%"></div>
      </div>
      <div class="productname">
        <p><%= @product.name %></p>
      </div>

      <div class="productdescription">
              <strong> Description:</strong>
        <p> <%= @product.description %></p>
      </div>

      <div class="productreviews">
          <h3>Reviews</h3>
          <% @product.reviews.each do |review| %>
          <p>
            <%= review.comment %>
          <br>
            Added on: <%= review.created_at %>
          </p>
          <% end %>
        </div>
      <div class="wrapper">
        <div class="newreview">
          <h3>New Review</h3>
          <%= render 'reviews/form', review: @review %>
          <%= link_to 'Edit', edit_product_path(@product) %> |
          <%= link_to 'Back', products_path %></strong>
          <p id="notice"><%= notice %></p>
         </div>
      </div>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>

  <% if @product.nil? %>
    <div class="field">
      <%= f.label :product_id %><br>
      <%= f.text_field :product_id %>
    </div>
  <% else %>
    <%= f.hidden_field :product_id, value: @product.id %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Product</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.comment %></td>
        <td><%= review.product.name %></td>
        <td><%= link_to 'Show', review %></td>
        <% if can? :edit, @review %>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <% if can? :edit, @review %>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>


<div class="new_review">
<%= link_to 'New Review', new_review_path %>
</div>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>Product:</strong>
  <%= @review.product.name %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |

<% if @review.product.nil? %>
  <%= link_to 'Back', reviews_path %>

<% else %>
  <%= link_to 'Back', @review.product %>
<% end %>

app/views/users/new.html.erb
<h1>Signup!</h1>
<div class="sign_up">
<%= form_for :user, url: '/users' do |f| %>
  <div class="form-item">Name: <%= f.text_field :name %></div>
  <div class="form-item">Email: <%= f.text_field :email %></div>
  <div class="form-item">Password: <%= f.password_field :password %></div>
<div class="form-item">Password Confirmation: <%= f.password_field :password_confirmation %></div>
  <div class="form-item"><%= f.submit "Submit" %></div>
<% end %>
</div>